---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

configMapGenerator:
  - name: script
    files:
      - mco-update-mgr.sh

resources:
  - cronjob.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - namespace.yaml

commonLabels:
  app.kubernetes.io/name: platform
